### ISSUE TITLE
¿puedo aportar en algo?

### ISSUE THREAD

**Issue by pachadotdev** [satRdays/santiago2018#2]
hola @rivaquiroga 
puedo hacer hartas cosas con blogdown/jekyll
react cacho poco pero no me queda tan feo

**Comment by jbkunst** [comment]
Hola @pachamaltese 

Por ahora no hay que hacer mucho. Solamente dejarlo funcional manteniendo el estándar/formato que satRdays utiliza. 

Por otra parte, se usa hugo a secas.
